// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1TxHZEEJg1BOSKcU3eQOvtcJOE2OBG0o',
    appId: '1:1081262854077:web:1ddc73f1f69e5687dc8cd4',
    messagingSenderId: '1081262854077',
    projectId: 'sirs-backend',
    authDomain: 'sirs-backend.firebaseapp.com',
    storageBucket: 'sirs-backend.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpfhn-nEHX3bHZzZTuwoj5uRDsKOxMzGA',
    appId: '1:1081262854077:android:40af42e91859ac75dc8cd4',
    messagingSenderId: '1081262854077',
    projectId: 'sirs-backend',
    storageBucket: 'sirs-backend.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDen6wulM1wh6Ih9PvnINQEjjW0Lcty9Aw',
    appId: '1:1081262854077:ios:49c4cfa947ad6587dc8cd4',
    messagingSenderId: '1081262854077',
    projectId: 'sirs-backend',
    storageBucket: 'sirs-backend.appspot.com',
    iosBundleId: 'com.sirs.sirsApps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDen6wulM1wh6Ih9PvnINQEjjW0Lcty9Aw',
    appId: '1:1081262854077:ios:49c4cfa947ad6587dc8cd4',
    messagingSenderId: '1081262854077',
    projectId: 'sirs-backend',
    storageBucket: 'sirs-backend.appspot.com',
    iosBundleId: 'com.sirs.sirsApps',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1TxHZEEJg1BOSKcU3eQOvtcJOE2OBG0o',
    appId: '1:1081262854077:web:0aa2cdaae42daa45dc8cd4',
    messagingSenderId: '1081262854077',
    projectId: 'sirs-backend',
    authDomain: 'sirs-backend.firebaseapp.com',
    storageBucket: 'sirs-backend.appspot.com',
  );
}
